import { createClient } from '@supabase/supabase-js';
import type { CreateOrderData, Order } from '@/lib/types/order.types';

const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
    throw new Error(
        'Supabase configuration missing. Please set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in your environment variables.'
    );
}

const supabase = createClient(supabaseUrl, supabaseKey);

export class OrderService {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    static mapRow(row: any): Order {
        return {
            id: row.id,
            orderNumber: row.order_number,
            customerName: row.customer_name,
            customerPhone: row.customer_phone,
            customerEmail: row.customer_email,
            modelId: row.model_id,
            fabricId: row.fabric_id,
            measurements: row.measurements,
            appointmentDate: row.appointment_date,
            location: row.location,
            specificLocation: row.specific_location,
            totalAmount: row.total_amount,
            paidAmount: row.paid_amount,
            paymentStatus: row.payment_status,
            paymentType: row.payment_type,
            status: row.status,
            transactionId: row.transaction_id,
            createdAt: row.created_at,
            updatedAt: row.updated_at,
        };
    }

    static async createOrder(data: Omit<CreateOrderData, 'orderNumber'>): Promise<Order> {
        try {
            // order_number is generated by the database (DEFAULT generate_order_number())
            const { data: order, error } = await supabase
                .from('orders')
                .insert({
                    customer_name: data.customerName,
                    customer_phone: data.customerPhone,
                    customer_email: data.customerEmail || null,
                    model_id: data.modelId,
                    fabric_id: data.fabricId,
                    measurements: data.measurements || null,
                    appointment_date: data.appointmentDate || null,
                    location: data.location,
                    specific_location: data.specificLocation || null,
                    total_amount: data.totalAmount,
                    paid_amount: data.paidAmount,
                    payment_status: data.paymentStatus,
                    payment_type: data.paymentType,
                    status: data.status,
                    transaction_id: data.transactionId || null,
                })
                .select()
                .single();

            if (error) {
                console.error('Database error creating order:', error);
                throw new Error('Failed to create order in database');
            }

            return OrderService.mapRow(order);
        } catch (error) {
            console.error('Order creation error:', error);
            throw error;
        }
    }

    /**
     * Get order by order number
     */
    static async getOrderByNumber(orderNumber: string): Promise<Order | null> {
        try {
            const { data, error } = await supabase
                .from('orders')
                .select('*')
                .eq('order_number', orderNumber)
                .single();

            if (error) {
                console.error('Error fetching order:', error);
                return null;
            }

            return OrderService.mapRow(data);
        } catch (error) {
            console.error('Get order error:', error);
            return null;
        }
    }

    /**
     * Update order payment status
     */
    static async updatePaymentStatus(
        orderNumber: string,
        paymentStatus: 'pending' | 'partial' | 'paid',
        paidAmount: number
    ): Promise<void> {
        try {
            const { error } = await supabase
                .from('orders')
                .update({
                    payment_status: paymentStatus,
                    paid_amount: paidAmount,
                    updated_at: new Date().toISOString(),
                })
                .eq('order_number', orderNumber);

            if (error) {
                console.error('Error updating payment status:', error);
                throw new Error('Failed to update payment status');
            }
        } catch (error) {
            console.error('Update payment status error:', error);
            throw error;
        }
    }
}
