// Données des modèles exportées pour réutilisation
export const modelsData = [
    {
        id: 1,
        image: '/models/example1.png',
        titre: 'Robe Élégante',
        description: 'Robe longue pour soirée',
        prix: 15000,
        type: 'Robe',
        designer: 'Élégance Paris',
        width: 1024,
        height: 1024
    },
    {
        id: 2,
        image: '/models/example2.jpg',
        titre: 'Tailleur Moderne',
        description: 'Ensemble professionnel chic',
        prix: 25000,
        type: 'Tailleur',
        designer: 'Chic Milano',
        width: 735,
        height: 934
    },
    {
        id: 3,
        image: '/models/example3.jpg',
        titre: 'Robe d\'Été',
        description: 'Légère et colorée',
        prix: 12000,
        type: 'Robe',
        designer: 'Summer Collection',
        width: 502,
        height: 743
    },
    {
        id: 4,
        image: '/models/example4.jpg',
        titre: 'Ensemble Casual',
        description: 'Confort et style',
        prix: 18000,
        type: 'Ensemble',
        designer: 'Urban Style',
        width: 736,
        height: 736
    },
    {
        id: 5,
        image: '/models/example5.jpg',
        titre: 'Veste Premium',
        description: 'Luxe et élégance',
        prix: 22000,
        type: 'Veste',
        designer: 'Élégance Paris',
        width: 736,
        height: 1008
    },
    {
        id: 6,
        image: '/models/example6.jpg',
        titre: 'Robe Cocktail',
        description: 'Parfaite pour vos soirées',
        prix: 20000,
        type: 'Robe',
        designer: 'Glamour Nights',
        width: 1170,
        height: 1260
    },
    {
        id: 7,
        image: '/models/example7.jpg',
        titre: 'Pantalon Chic',
        description: 'Coupe moderne',
        prix: 14000,
        type: 'Pantalon',
        designer: 'Chic Milano',
        width: 736,
        height: 1308
    },
    {
        id: 8,
        image: '/models/example8.jpg',
        titre: 'Collection Luxe',
        description: 'Pièce unique et raffinée',
        prix: 35000,
        type: 'Ensemble',
        designer: 'Haute Couture',
        width: 736,
        height: 736
    },
    {
        id: 9,
        image: '/models/example9.jpg',
        titre: 'Top Sophistiqué',
        description: 'Haut élégant pour toutes occasions',
        prix: 10000,
        type: 'Top',
        designer: 'Urban Style',
        width: 736,
        height: 1104
    },
    {
        id: 10,
        image: '/models/example10.jpg',
        titre: 'Robe de Mariée',
        description: 'Créations sur mesure',
        prix: 50000,
        type: 'Robe',
        designer: 'Haute Couture',
        width: 736,
        height: 700
    },
    {
        id: 11,
        image: '/models/example11.jpg',
        titre: 'Costume Sur-Mesure',
        description: 'Élégance masculine raffinée',
        prix: 30000,
        type: 'Costume',
        designer: 'Chic Milano',
        width: 1080,
        height: 1274
    },
    {
        id: 12,
        image: '/models/example12.jpg',
        titre: 'Jupe Plissée',
        description: 'Style intemporel et féminin',
        prix: 8000,
        type: 'Jupe',
        designer: 'Summer Collection',
        width: 526,
        height: 526
    },
    {
        id: 13,
        image: '/models/example13.jpg',
        titre: 'Manteau d\'Hiver',
        description: 'Chaleur et style réunis',
        prix: 28000,
        type: 'Manteau',
        designer: 'Élégance Paris',
        width: 736,
        height: 736
    },
    {
        id: 14,
        image: '/models/example14.jpg',
        titre: 'Chemise Classique',
        description: 'Basique revisité avec élégance',
        prix: 9000,
        type: 'Chemise',
        designer: 'Urban Style',
        width: 635,
        height: 619
    },
    {
        id: 15,
        image: '/models/example15.jpg',
        titre: 'Ensemble Sportswear',
        description: 'Confort et modernité',
        prix: 16000,
        type: 'Ensemble',
        designer: 'Urban Style',
        width: 736,
        height: 736
    },
    {
        id: 16,
        image: '/models/example16.jpg',
        titre: 'Accessoires Luxe',
        description: 'Compléter votre look avec style',
        prix: 12000,
        type: 'Accessoire',
        designer: 'Glamour Nights',
        width: 686,
        height: 1200
    },
    {
        id: 17,
        image: '/models/example1.png',
        titre: 'Robe de Soirée Dorée',
        description: 'Éclat et sophistication',
        prix: 45000,
        type: 'Robe',
        designer: 'Haute Couture',
        width: 1024,
        height: 1024
    },
    {
        id: 18,
        image: '/models/example2.jpg',
        titre: 'Blazer Moderne',
        description: 'Pour un look professionnel',
        prix: 28000,
        type: 'Veste',
        designer: 'Chic Milano',
        width: 735,
        height: 934
    },
    {
        id: 19,
        image: '/models/example3.jpg',
        titre: 'Robe Bohème',
        description: 'Style décontracté et chic',
        prix: 18000,
        type: 'Robe',
        designer: 'Summer Collection',
        width: 502,
        height: 743
    },
    {
        id: 20,
        image: '/models/example4.jpg',
        titre: 'Tenue de Sport Chic',
        description: 'Confort et élégance réunis',
        prix: 22000,
        type: 'Ensemble',
        designer: 'Urban Style',
        width: 736,
        height: 736
    },
    {
        id: 21,
        image: '/models/example5.jpg',
        titre: 'Veste en Cuir',
        description: 'Style rock et élégant',
        prix: 38000,
        type: 'Veste',
        designer: 'Élégance Paris',
        width: 736,
        height: 1008
    },
    {
        id: 22,
        image: '/models/example6.jpg',
        titre: 'Robe de Gala',
        description: 'Pour les grandes occasions',
        prix: 55000,
        type: 'Robe',
        designer: 'Haute Couture',
        width: 1170,
        height: 1260
    },
    {
        id: 23,
        image: '/models/example7.jpg',
        titre: 'Pantalon Large',
        description: 'Tendance et confortable',
        prix: 16000,
        type: 'Pantalon',
        designer: 'Urban Style',
        width: 736,
        height: 1308
    },
    {
        id: 24,
        image: '/models/example8.jpg',
        titre: 'Ensemble Cérémonie',
        description: 'Pour vos événements spéciaux',
        prix: 42000,
        type: 'Ensemble',
        designer: 'Glamour Nights',
        width: 736,
        height: 736
    },
];
